name: Deploy to EC2

on:
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t qkrtjdgh320/react-nginx:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push qkrtjdgh320/react-nginx:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull qkrtjdgh320/react-nginx:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 80:80 qkrtjdgh320/react-nginx:latest
